from django.conf.urls import patterns, url

urlpatterns = patterns('personal.views',
    url(r'^register/$', 'register', name='register'),
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^(?P<send_param>profile)/(?P<token>\w+)$', 'profile_mail', name='token_profile'),
    url(r'^profile/$', 'profile', name='profile'),
    url(r'^settings/$', 'profile_settings', name='profile_set'),
    url(r'^get_pay/$', 'get_pay', name='get_pay'),
    url(r'^get_pay_btns/$', 'get_pay_btns', name='get_pay_btns'),
    url(r'^get_base_prices/$', 'get_base_prices'),
    url(r'^liqpay/result$', 'liqpay', name='liqpay'),
    url(r'^webmoney/result/$', 'webmoney_result', name='webmoney_result'),
    url(r'^ab_status/$', 'ab_status', name='ab_status'),
    url(r'^user_question/$', 'user_question', name='user_question'),
    url(r'^admin_shaman/', 'admin_ch_user_pass', name='admin_ch_user_pass'),
    url(r'^adm_send_mail/', 'adm_send_mail'),
    url(r'^adm_add_phone/', 'adm_add_phone'),
    url(r'^adm_change_comment/', 'adm_change_comment'),
    url(r'^payment_report', 'payment_report', name='payment_report'),
    url(r'^pay_service', 'pay_from_balance'),
    url(r'^ulogin', 'ulogin'),
    url(r'^social/new/(?P<token>\w+)/$', 'social_new', name='social_new'),
    url(r'^social/mail_confirm/(?P<token>\w+)$', 'social_mail_confirm',
        name='social_mail_confirm'),
)
# views are in django.contrib.auth.views
urlpatterns += patterns('django.contrib.auth.views',
    url(r'^password/reset/$', 'password_reset',
        {'post_reset_redirect': '/accounts/password/reset/done/'}, name='password_reset'),
    url(r'^password/reset/done/$', 'password_reset_done'),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'password_reset_confirm_uidb36'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^password/done/$', 'password_reset_complete', name='password_reset_complete'),
)
